---
- name: Restart systemd-sysctl
  ansible.builtin.service:
    name: systemd-sysctl
    state: restarted

- name: Restart keepalived
  ansible.builtin.service:
    name: keepalived
    state: restarted
